### ISSUE TITLE
On Tableau Server switching tabs away from one containing an extension throws continuous permission denied errors in IE11 / Edge

### ISSUE THREAD

**Issue by ugamarkj** [tableau/extensions-api#182]
I also have an open support case for this, but posting here as well in case others are receiving the error.

![image](https://user-images.githubusercontent.com/21127705/50059227-07b8ac00-0152-11e9-8523-07437b0a1ab0.png)

**Comment by ArunSanthosh** [comment]
John,
I just encountered this issue in my multi tab dashboard as well.
Works perfectly fine in firefox but gets repeated access denied in IE edge.

I see your note that this fix is available in 2019.1.
Just to be sure - you are talking of server version upgrade; not extension bundle, right?
I see server 2019.1 beta is available. Any idea on when the prod ready version will be released?
Please let me know. Thanks.

Regards,
Arun Santhosh

**Comment by ArunSanthosh** [comment]
John, 
Follow up question - Is there any workaround that can be applied to 2018.2 version ?
(Is this at all related to CORS and will opening up extension URL for CORS help any? )

Regards,
Arun Santhosh

**Comment by johnDance** [comment]
Hi Arun
> Just to be sure - you are talking of server version upgrade; not extension bundle, right?
Correct, the fix is internal to Tableau. 

> I see server 2019.1 beta is available. Any idea on when the prod ready version will be released?
It is scheduled for releasing to operations very soon. I'm afraid I don't know how long it takes from there to the public. But it is week(s), not months.

> Follow up question - Is there any workaround that can be applied to 2018.2 version ?
I was not involved in this change. Let me check if that is feasible, and get back to you.

John

**Comment by johnDance** [comment]
Well that was a quick follow up. (Under 10 minutes!) The engineer involved in the change reports that he ported the fix to both dot releases of 18.2 and 18.3. It should be available in 2018.2.5 and 2018.3.2.

John

**Comment by thecarlmartin** [comment]
Seems the like the fix wasn't successful. We still experience the issue with our Tableau Server deployment with IE11 and with Edge.

**Comment by kartheekchk86** [comment]
This issue still exists. I am using 2019.2. I use chrome and never seen it but all my customers use IE and blasted me..

**Comment by bcantoni** [comment]
Closing out as fixed based on the discussion above. If this is still an issue, please reopen with a comment on the latest status and we can revisit.

Also, in 2020 Tableau officially stopped supporting IE11, so these types of issues would probably not be fixed
